create table if not exists public.clinic_settings (
  id text primary key default 'as-estetica',
  slug text not null default 'clinica-bela',
  name text not null default 'AS Estética',
  description text,
  address text,
  phone text,
  email text,
  website text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.clinic_working_hours (
  id bigint generated by default as identity primary key,
  clinic_id text not null default 'as-estetica' references public.clinic_settings(id) on delete cascade,
  weekday integer not null check (weekday between 0 and 6),
  is_open boolean not null default false,
  opens_at text,
  closes_at text,
  pause_starts_at text,
  pause_ends_at text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (clinic_id, weekday)
);

insert into public.clinic_settings (id, slug, name, description, address, phone, email, website)
values (
  'as-estetica',
  'clinica-bela',
  'AS Estética',
  'Cuidado, bem-estar e estética em um só lugar.',
  'Rua Deputado João Henrique, 178B, segundo andar, Bairro de Fátima',
  '+55 98 97009-4566',
  'contato@asestetica.com.br',
  'https://www.asestetica.com.br/pg-asclinica'
)
on conflict (id) do nothing;

insert into public.clinic_working_hours (clinic_id, weekday, is_open, opens_at, closes_at, pause_starts_at, pause_ends_at)
values
  ('as-estetica', 0, true, '08:00', '12:00', null, null),
  ('as-estetica', 1, false, '09:00', '18:00', null, null),
  ('as-estetica', 2, true, '09:00', '18:00', null, null),
  ('as-estetica', 3, true, '09:00', '18:00', null, null),
  ('as-estetica', 4, true, '09:00', '18:00', null, null),
  ('as-estetica', 5, true, '09:00', '18:00', null, null),
  ('as-estetica', 6, true, '08:00', '12:00', null, null)
on conflict (clinic_id, weekday) do nothing;

alter table public.clinic_settings enable row level security;
alter table public.clinic_working_hours enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'clinic_settings'
      and policyname = 'Anyone can read clinic settings'
  ) then
    create policy "Anyone can read clinic settings"
      on public.clinic_settings
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'clinic_settings'
      and policyname = 'Authenticated can manage clinic settings'
  ) then
    create policy "Authenticated can manage clinic settings"
      on public.clinic_settings
      for all
      to authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'clinic_working_hours'
      and policyname = 'Anyone can read clinic working hours'
  ) then
    create policy "Anyone can read clinic working hours"
      on public.clinic_working_hours
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'clinic_working_hours'
      and policyname = 'Authenticated can manage clinic working hours'
  ) then
    create policy "Authenticated can manage clinic working hours"
      on public.clinic_working_hours
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;
